env: dev
default_gateway: 192.168.0.1
default_network_interface: en0
status_led: 17
connection_timeout: 0.25
log_level: DEBUG
mqtt_config:
    broker_config:
        host: homeassistant.local
        port: 1883
        username: test
        password: test
strip_config:
    brightness: 255
    channel: 0
    dma: 10
    freq_hz: 800000
    invert: False
    pin: 18
    strip_length: 300
    sections:
        - ha_name: WS2812B strip section 1
          ha_entity_id: ws2812b_strip_section_1
          start: 0
          end: 99
        - ha_name: WS2812B strip section 1
          ha_entity_id: ws2812b_strip_section_2
          start: 100
          end: 199